"""empty message

Revision ID: b16c6b7dd711
Revises: 
Create Date: 2019-11-13 22:44:50.042500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16c6b7dd711'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('deal', sa.Integer(), nullable=True),
    sa.Column('cat', sa.Text(), nullable=True),
    sa.Column('subcat', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('nVotes', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.Column('imageURL', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('asin')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('userEmail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asin'], ['products.asin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asin'], ['products.asin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('emails')
    op.drop_table('products')
    # ### end Alembic commands ###
